import Head from "next/head";
import hljs from "highlight.js/lib/core";
import javascript from "highlight.js/lib/languages/javascript";
import Image from "next/image";
import styles from "../styles/Home.module.css";

hljs.registerLanguage("javascript", javascript);

export default function Home() {
  const codesnippet = `const express = require("express");\nvar a = "hola";\nfunction saludar(name) {\n console.log(name)\n}\nfor(let i = 0; i < arr.length; i++) {\n return arr[i]+1\n}`;

  const codecontent = hljs.highlight(codesnippet, {
    language: "javascript",
  }).value;
  return (
    <div className={styles.container}>
      <Head>
        <title>Code Highlight</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a href="https://www.npmjs.com/package/highlight.js?activeTab=readme">
            Highlight.js
          </a>
        </h1>

        <pre>
          <code dangerouslySetInnerHTML={{ __html: codecontent }} />
        </pre>

        <p>npm i highlight.js</p>
      </main>
    </div>
  );
}
